import type { MplusBeacon } from "@/phenomenal/types/mplus";

/**
 * Дерево проекта — те же beacon-узлы, что и M+, но описывают структуру программы.
 * Каждый узел = раздел/файл проекта, к которому привязан вопрос.
 *
 * Уровни:
 *   1 — корень (сам проект)
 *   2 — слои: app, core, phenomenal, modules, shared
 *   3 — подсистемы внутри слоя
 *   4 — конкретные файлы (листья)
 */
export const projectTree: MplusBeacon[] = [
  // ── Уровень 1: корень ─────────────────────────────────────────────────────
  {
    id: "proj-root",
    distance: 1,
    questionId: "pq-root",
    parent: null,
    children: ["proj-app", "proj-core", "proj-phenomenal", "proj-modules", "proj-shared"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },

  // ── Уровень 2: слои ───────────────────────────────────────────────────────
  {
    id: "proj-app",
    distance: 2,
    questionId: "pq-app",
    parent: "proj-root",
    children: ["proj-app-routing", "proj-app-actions", "proj-app-api"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-core",
    distance: 2,
    questionId: "pq-core",
    parent: "proj-root",
    children: ["proj-core-auth", "proj-core-db"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-phenomenal",
    distance: 2,
    questionId: "pq-phenomenal",
    parent: "proj-root",
    children: ["proj-engine", "proj-mplus", "proj-r"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-modules",
    distance: 2,
    questionId: "pq-modules",
    parent: "proj-root",
    children: ["proj-mod-auth", "proj-mod-dashboard"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-shared",
    distance: 2,
    questionId: "pq-shared",
    parent: "proj-root",
    children: ["proj-shared-ui", "proj-shared-lib"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },

  // ── Уровень 3: подсистемы ─────────────────────────────────────────────────
  {
    id: "proj-app-routing",
    distance: 3,
    questionId: "pq-app-routing",
    parent: "proj-app",
    children: ["proj-app-page", "proj-app-layout"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-app-actions",
    distance: 3,
    questionId: "pq-app-actions",
    parent: "proj-app",
    children: ["proj-save-flow-action"],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-app-api",
    distance: 3,
    questionId: "pq-app-api",
    parent: "proj-app",
    children: ["proj-api-auth", "proj-api-flows"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-core-auth",
    distance: 3,
    questionId: "pq-core-auth",
    parent: "proj-core",
    children: ["proj-session", "proj-password", "proj-guards"],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-core-db",
    distance: 3,
    questionId: "pq-core-db",
    parent: "proj-core",
    children: ["proj-schema", "proj-flows-db"],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-engine",
    distance: 3,
    questionId: "pq-engine",
    parent: "proj-phenomenal",
    children: ["proj-engine-start", "proj-engine-answer", "proj-engine-next"],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-mplus",
    distance: 3,
    questionId: "pq-mplus",
    parent: "proj-phenomenal",
    children: ["proj-mplus-tree", "proj-select-next"],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-r",
    distance: 3,
    questionId: "pq-r",
    parent: "proj-phenomenal",
    children: ["proj-questions"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-mod-auth",
    distance: 3,
    questionId: "pq-mod-auth",
    parent: "proj-modules",
    children: ["proj-auth-api", "proj-login-form"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-mod-dashboard",
    distance: 3,
    questionId: "pq-mod-dashboard",
    parent: "proj-modules",
    children: ["proj-stats-card"],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-shared-ui",
    distance: 3,
    questionId: "pq-shared-ui",
    parent: "proj-shared",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-shared-lib",
    distance: 3,
    questionId: "pq-shared-lib",
    parent: "proj-shared",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },

  // ── Уровень 4: конкретные файлы (листья) ─────────────────────────────────
  {
    id: "proj-app-page",
    distance: 4,
    questionId: "pq-app-page",
    parent: "proj-app-routing",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-app-layout",
    distance: 4,
    questionId: "pq-app-layout",
    parent: "proj-app-routing",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-save-flow-action",
    distance: 4,
    questionId: "pq-save-flow-action",
    parent: "proj-app-actions",
    children: [],
    f: 0,
    importance: 3,
    type: ["Project"],
  },
  {
    id: "proj-api-auth",
    distance: 4,
    questionId: "pq-api-auth",
    parent: "proj-app-api",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-api-flows",
    distance: 4,
    questionId: "pq-api-flows",
    parent: "proj-app-api",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-session",
    distance: 4,
    questionId: "pq-session",
    parent: "proj-core-auth",
    children: [],
    f: 0,
    importance: 3,
    type: ["Project"],
  },
  {
    id: "proj-password",
    distance: 4,
    questionId: "pq-password",
    parent: "proj-core-auth",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-guards",
    distance: 4,
    questionId: "pq-guards",
    parent: "proj-core-auth",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-schema",
    distance: 4,
    questionId: "pq-schema",
    parent: "proj-core-db",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-flows-db",
    distance: 4,
    questionId: "pq-flows-db",
    parent: "proj-core-db",
    children: [],
    f: 0,
    importance: 3,
    type: ["Project"],
  },
  {
    id: "proj-engine-start",
    distance: 4,
    questionId: "pq-engine-start",
    parent: "proj-engine",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-engine-answer",
    distance: 4,
    questionId: "pq-engine-answer",
    parent: "proj-engine",
    children: [],
    f: 0,
    importance: 3,
    type: ["Project"],
  },
  {
    id: "proj-engine-next",
    distance: 4,
    questionId: "pq-engine-next",
    parent: "proj-engine",
    children: [],
    f: 0,
    importance: 3,
    type: ["Project"],
  },
  {
    id: "proj-mplus-tree",
    distance: 4,
    questionId: "pq-mplus-tree",
    parent: "proj-mplus",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-select-next",
    distance: 4,
    questionId: "pq-select-next",
    parent: "proj-mplus",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-questions",
    distance: 4,
    questionId: "pq-questions",
    parent: "proj-r",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-auth-api",
    distance: 4,
    questionId: "pq-auth-api",
    parent: "proj-mod-auth",
    children: [],
    f: 0,
    importance: 2,
    type: ["Project"],
  },
  {
    id: "proj-login-form",
    distance: 4,
    questionId: "pq-login-form",
    parent: "proj-mod-auth",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
  {
    id: "proj-stats-card",
    distance: 4,
    questionId: "pq-stats-card",
    parent: "proj-mod-dashboard",
    children: [],
    f: 0,
    importance: 1,
    type: ["Project"],
  },
];

export function findProjectBeaconById(id: string): MplusBeacon | null {
  return projectTree.find((b) => b.id === id) ?? null;
}

export function findProjectBeaconByQuestionId(questionId: string): MplusBeacon | null {
  return projectTree.find((b) => b.questionId === questionId) ?? null;
}
