import type { RQuestion } from "@/phenomenal/types/r";

export function findProjectQuestionById(id: string): RQuestion | null {
  return projectQuestions.find((q) => q.id === id) ?? null;
}

/**
 * Вопросы о структуре проекта next-learning.
 * Каждый вопрос привязан к beacon-узлу в project-tree.ts через beaconId.
 * Поле code — путь к файлу или фрагмент кода из проекта.
 */
export const projectQuestions: RQuestion[] = [
  // ── Уровень 1: корень ─────────────────────────────────────────────────────
  {
    id: "pq-root",
    beaconId: "proj-root",
    code: "next-learning/",
    question: "На каком фреймворке построено это приложение?",
    correct: "Next.js 16 с App Router и React 19",
    wrong: [
      "Vite + Vue 3",
      "Create React App (CRA)",
      "Remix + React 18",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "nextjs", "framework"],
  },

  // ── Уровень 2: слои ───────────────────────────────────────────────────────
  {
    id: "pq-app",
    beaconId: "proj-app",
    code: "src/app/",
    question: "Что хранится в папке src/app/?",
    correct: "Страницы, API-роуты и Server Actions — маршрутизация Next.js App Router",
    wrong: [
      "Только React-компоненты без маршрутов",
      "Только статические файлы (CSS, изображения)",
      "Бизнес-логика и движок квиза",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "app-router", "routing"],
  },
  {
    id: "pq-core",
    beaconId: "proj-core",
    code: "src/core/",
    question: "Что находится в папке src/core/?",
    correct: "Инфраструктура: подключение к БД, авторизация (JWT, bcrypt), конфиг",
    wrong: [
      "UI-компоненты кнопок и инпутов",
      "Квиз-движок: start, answer, next, finish",
      "Данные вопросов и принципов",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "core", "infrastructure"],
  },
  {
    id: "pq-phenomenal",
    beaconId: "proj-phenomenal",
    code: "src/phenomenal/",
    question: "Что содержит папка src/phenomenal/?",
    correct: "Весь квиз-движок: дерево M+, вопросы, engine-функции, UI-компоненты, типы",
    wrong: [
      "Только REST API роуты",
      "Только подключение к базе данных",
      "Только React-хуки",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "phenomenal", "quiz-engine"],
  },
  {
    id: "pq-modules",
    beaconId: "proj-modules",
    code: "src/modules/",
    question: "По какому принципу организованы файлы в src/modules/?",
    correct: "По фичам (feature-modules): auth, dashboard, users — каждый со своими api/, components/, model/",
    wrong: [
      "По типам файлов: все компоненты вместе, все типы вместе",
      "По страницам: один модуль = одна страница",
      "По алфавиту без смысловой группировки",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "modules", "architecture"],
  },
  {
    id: "pq-shared",
    beaconId: "proj-shared",
    code: "src/shared/",
    question: "Что хранится в src/shared/?",
    correct: "Переиспользуемые утилиты и UI-примитивы: Button, Card, Input, cn(), formatDate, хуки",
    wrong: [
      "Секретные ключи и переменные окружения",
      "Drizzle ORM схемы таблиц",
      "Server Actions для форм",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "shared", "utilities"],
  },

  // ── Уровень 3: подсистемы ─────────────────────────────────────────────────
  {
    id: "pq-app-routing",
    beaconId: "proj-app-routing",
    code: "src/app/page.tsx\nsrc/app/layout.tsx",
    question: "Что делает файл src/app/layout.tsx в Next.js App Router?",
    correct: "Оборачивает все страницы: задаёт шрифты, <html>, <body> и глобальные стили",
    wrong: [
      "Хранит маршруты в виде массива путей",
      "Отвечает только за роутинг между /quiz и /auth",
      "Является Server Action для навигации",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "layout", "app-router"],
  },
  {
    id: "pq-app-actions",
    beaconId: "proj-app-actions",
    code: "src/app/actions/flows.actions.ts",
    question: "Что такое Server Action и что делает директива 'use server'?",
    correct: "Помечает функцию как серверную — Next.js выполняет её на сервере, вызов возможен из Client Component без fetch()",
    wrong: [
      "Запускает функцию в Web Worker браузера",
      "Кэширует результат функции на 60 секунд",
      "Преобразует функцию в API Route",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "server-action", "nextjs"],
  },
  {
    id: "pq-app-api",
    beaconId: "proj-app-api",
    code: "src/app/api/auth/login/route.ts",
    question: "Как Next.js определяет, что файл является API Route?",
    correct: "По имени файла route.ts внутри папки app/api/ — он экспортирует функции GET, POST и др.",
    wrong: [
      "Через специальный декоратор @ApiRoute над функцией",
      "По расширению файла .api.ts",
      "Через конфиг в next.config.ts",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "api-route", "nextjs"],
  },
  {
    id: "pq-core-auth",
    beaconId: "proj-core-auth",
    code: "src/core/auth/",
    question: "Какие две технологии используются для авторизации в src/core/auth/?",
    correct: "bcryptjs — хеширование паролей, jose — создание и проверка JWT токенов",
    wrong: [
      "passport.js и express-session",
      "Auth.js (NextAuth) и Prisma",
      "Firebase Auth и Google OAuth",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "auth", "bcrypt", "jwt"],
  },
  {
    id: "pq-core-db",
    beaconId: "proj-core-db",
    code: "src/core/db/",
    question: "Какая база данных и какой ORM используются в проекте?",
    correct: "Neon PostgreSQL (serverless) + Drizzle ORM",
    wrong: [
      "SQLite + Prisma ORM",
      "MongoDB Atlas + Mongoose",
      "PlanetScale MySQL + TypeORM",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "database", "drizzle", "neon"],
  },
  {
    id: "pq-engine",
    beaconId: "proj-engine",
    code: "src/phenomenal/engine/",
    question: "Все функции в src/phenomenal/engine/ — чистые. Что это означает?",
    correct: "Они не изменяют внешнее состояние — получают QuizState и возвращают новый QuizState",
    wrong: [
      "Они вызываются только на сервере",
      "Они сохраняют результат в localStorage автоматически",
      "Они являются React-хуками",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "engine", "pure-functions"],
  },
  {
    id: "pq-mplus",
    beaconId: "proj-mplus",
    code: "src/phenomenal/mplus/",
    question: "Что такое beacon (узел) в системе M+?",
    correct: "Узел дерева навигации — хранит ссылку на вопрос (questionId), дочерние узлы и статистику частоты",
    wrong: [
      "React-компонент для отображения одного вопроса",
      "HTTP-запрос к API за следующим вопросом",
      "Запись в таблице quiz_flow_steps",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "mplus", "beacon", "tree"],
  },
  {
    id: "pq-r",
    beaconId: "proj-r",
    code: "src/phenomenal/r/questions.ts",
    question: "Что хранит папка src/phenomenal/r/?",
    correct: "Вопросы (RQuestion): текст, правильный ответ, три неправильных варианта, теги",
    wrong: [
      "Принципы и правила (rf-система)",
      "HTTP-клиент для загрузки вопросов с сервера",
      "Результаты завершённых потоков",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "questions", "r-system"],
  },
  {
    id: "pq-mod-auth",
    beaconId: "proj-mod-auth",
    code: "src/modules/auth/",
    question: "Чем отличается src/modules/auth/ от src/core/auth/?",
    correct: "modules/auth — UI и fetch-клиент (LoginForm, SignupForm, authApi); core/auth — серверная логика (JWT, bcrypt, guards)",
    wrong: [
      "modules/auth для страниц, core/auth для тестов",
      "modules/auth для Next.js 16, core/auth для старых версий",
      "Никакой разницы, это дублирование кода",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "auth", "modules", "separation"],
  },
  {
    id: "pq-mod-dashboard",
    beaconId: "proj-mod-dashboard",
    code: "src/modules/dashboard/components/DashboardGrid.tsx",
    question: "Что показывает DashboardGrid в модуле dashboard?",
    correct: "Сетку карточек статистики: score, importance, количество потоков пользователя",
    wrong: [
      "Дерево M+ в виде SVG-графики",
      "Таблицу всех вопросов с фильтрацией",
      "Форму создания нового квиза",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "dashboard", "ui"],
  },
  {
    id: "pq-shared-ui",
    beaconId: "proj-shared-ui",
    code: "src/shared/ui/Button.tsx",
    question: "Зачем нужны компоненты Button, Card, Input в src/shared/ui/?",
    correct: "Переиспользуемые примитивы с едиными стилями — чтобы не дублировать Tailwind-классы по всему проекту",
    wrong: [
      "Это копии компонентов из библиотеки shadcn/ui",
      "Они нужны только для страниц /auth",
      "Это автоматически сгенерированные файлы Next.js",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "shared", "ui-primitives"],
  },
  {
    id: "pq-shared-lib",
    beaconId: "proj-shared-lib",
    code: "src/shared/lib/cn.ts",
    question: "Что делает функция cn() из src/shared/lib/cn.ts?",
    correct: "Объединяет className строки с dedupe через clsx — удобно для условных Tailwind-классов",
    wrong: [
      "Подключает CSS-модули к компоненту",
      "Конвертирует px в rem для адаптивности",
      "Генерирует уникальные CSS-переменные",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "shared", "cn", "tailwind"],
  },

  // ── Уровень 4: конкретные файлы ───────────────────────────────────────────
  {
    id: "pq-app-page",
    beaconId: "proj-app-page",
    code: "// src/app/page.tsx\nexport default function HomePage() { ... }",
    question: "src/app/page.tsx — это Server Component или Client Component?",
    correct: "Server Component — нет директивы 'use client', выполняется на сервере, HTML отправляется браузеру",
    wrong: [
      "Client Component — потому что содержит JSX",
      "Гибридный компонент — первый рендер на сервере, второй на клиенте",
      "API Route — потому что находится в папке app/",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "server-component", "page"],
  },
  {
    id: "pq-app-layout",
    beaconId: "proj-app-layout",
    code: "// src/app/layout.tsx\nexport default function RootLayout({ children }: ...) {}",
    question: "Сколько раз Next.js рендерит layout.tsx при навигации между страницами?",
    correct: "Только один раз при первой загрузке — при клиентской навигации layout не перерендеривается",
    wrong: [
      "При каждом переходе между страницами",
      "Никогда — он исполняется только на клиенте",
      "Два раза: при SSR и при гидратации",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "layout", "nextjs", "rendering"],
  },
  {
    id: "pq-save-flow-action",
    beaconId: "proj-save-flow-action",
    code: "'use server';\nexport async function saveFlowAction(flow, sequence) {\n  const session = await readSessionFromCookie();\n  if (!session) return { ok: false, reason: 'not_authenticated' };\n  await saveFlowForUser(...);\n  return { ok: true };\n}",
    question: "Что происходит если saveFlowAction() вернул { ok: false, reason: 'not_authenticated' }?",
    correct: "QuizPage переключается на fallback: сохраняет поток в localStorage через saveFlow()",
    wrong: [
      "Приложение выбрасывает ошибку 401 и перенаправляет на /auth",
      "Поток теряется — нет ни БД, ни localStorage",
      "Server Action повторяет попытку автоматически через 3 секунды",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["project", "server-action", "fallback", "auth"],
  },
  {
    id: "pq-api-auth",
    beaconId: "proj-api-auth",
    code: "// POST /api/auth/login\nconst { email, password } = await req.json();\nconst user = await findUserByEmail(email);\nconst ok = await verifyPassword(password, user.passwordHash);",
    question: "Где хранится токен сессии после успешного входа?",
    correct: "В httpOnly cookie nl_session — браузер не может читать её через JavaScript (защита от XSS)",
    wrong: [
      "В localStorage под ключом 'token'",
      "В React-состоянии через useState",
      "В sessionStorage, очищается при закрытии вкладки",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "auth", "cookie", "security"],
  },
  {
    id: "pq-api-flows",
    beaconId: "proj-api-flows",
    code: "// GET /api/flows — возвращает потоки пользователя\n// POST /api/flows — сохраняет поток",
    question: "Зачем нужен /api/flows, если есть Server Action saveFlowAction()?",
    correct: "flowsApi.list() читает список потоков с сервера — Server Action только сохраняет, а GET нужен для загрузки",
    wrong: [
      "Это устаревший код, который уже не используется",
      "Server Action не умеет возвращать данные, только сохранять",
      "/api/flows для анонимных пользователей, Server Action для авторизованных",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "api", "flows", "server-action"],
  },
  {
    id: "pq-session",
    beaconId: "proj-session",
    code: "// src/core/auth/session.ts\nexport async function readSessionFromCookie(): Promise<JwtPayload | null>",
    question: "Что делает readSessionFromCookie() в session.ts?",
    correct: "Читает cookie nl_session, верифицирует JWT подпись через jose и возвращает payload с userId (sub)",
    wrong: [
      "Читает userId из localStorage",
      "Делает fetch к /api/auth/me для проверки токена",
      "Создаёт новую сессию если старая истекла",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["project", "session", "jwt", "cookie"],
  },
  {
    id: "pq-password",
    beaconId: "proj-password",
    code: "// src/core/auth/password.ts\nawait bcrypt.hash(password, 12)\nawait bcrypt.compare(password, hash)",
    question: "Почему bcrypt с rounds=12, а не просто SHA-256?",
    correct: "bcrypt намеренно медленный — подбор одного пароля занимает ~250мс, что делает brute-force практически невозможным",
    wrong: [
      "SHA-256 не поддерживается в Node.js",
      "bcrypt короче в коде, поэтому выбран для простоты",
      "bcrypt хранит соль отдельно в БД, SHA-256 — нет",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "password", "bcrypt", "security"],
  },
  {
    id: "pq-guards",
    beaconId: "proj-guards",
    code: "// src/core/auth/guards.ts\nexport async function requireAuth(req: Request): Promise<JwtPayload>",
    question: "Что делает requireAuth() и где она используется?",
    correct: "Проверяет сессию в API Route — если не авторизован, выбрасывает ошибку 401; используется в route.ts Guard",
    wrong: [
      "Перенаправляет пользователя на /auth через redirect()",
      "Проверяет права доступа (admin/user) для роутов",
      "Используется в Client Component для защиты кнопок",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "guards", "auth", "api"],
  },
  {
    id: "pq-schema",
    beaconId: "proj-schema",
    code: "// src/core/db/schema.ts\nexport const users = pgTable('users', { ... })\nexport const quizFlows = pgTable('quiz_flows', { ... })\nexport const quizFlowSteps = pgTable('quiz_flow_steps', { ... })",
    question: "Сколько таблиц определено в schema.ts и что они хранят?",
    correct: "3 таблицы: users (аккаунты), quiz_flows (один поток целиком), quiz_flow_steps (каждый шаг потока)",
    wrong: [
      "5 таблиц: добавлены sessions и principles",
      "2 таблицы: users и flows (шаги внутри flows как JSON)",
      "1 таблица: всё хранится в одной quiz_data как JSONB",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "schema", "database", "drizzle"],
  },
  {
    id: "pq-flows-db",
    beaconId: "proj-flows-db",
    code: "// src/core/db/flows.ts\nawait db.transaction(async (trx) => {\n  await trx.insert(quizFlows).values(...);\n  await trx.insert(quizFlowSteps).values(...);\n});",
    question: "Зачем saveFlowForUser() использует транзакцию?",
    correct: "Чтобы quiz_flows и quiz_flow_steps записывались атомарно — либо оба успешно, либо ни один",
    wrong: [
      "Транзакция ускоряет вставку двух запросов",
      "Drizzle требует транзакцию для любых INSERT",
      "Транзакция нужна для обхода ограничений на размер запроса",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["project", "database", "transaction", "drizzle"],
  },
  {
    id: "pq-engine-start",
    beaconId: "proj-engine-start",
    code: "export function startQuiz(mode = 'random'): QuizState {\n  return {\n    currentBeacon: findBeaconById('mplus-root'),\n    steps: [],\n    finished: false,\n    mode,\n  };\n}",
    question: "С какого узла всегда начинается квиз и почему?",
    correct: "С 'mplus-root' — корня дерева M+, который является единственным узлом без parent (parent: null)",
    wrong: [
      "Со случайного листового узла для разнообразия",
      "С узла с наибольшей importance",
      "С последнего посещённого узла из localStorage",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "engine", "start", "mplus"],
  },
  {
    id: "pq-engine-answer",
    beaconId: "proj-engine-answer",
    code: "// answerQuestion() вызывает:\nupdateQuestion(question.id, { importance, incrementFrequency: true });\nupdateBeaconFrequency(beacon.id);\nupdateBeaconImportance(beacon.id, importance);",
    question: "Где хранится обновлённая статистика вопросов после ответа пользователя?",
    correct: "В памяти (in-memory) — в массивах questions[] и mplusTree[]; при перезагрузке страницы сбрасывается",
    wrong: [
      "Немедленно в Neon PostgreSQL через Drizzle",
      "В localStorage через saveFlow()",
      "В React-состоянии через useState в QuizPage",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["project", "engine", "answer", "state"],
  },
  {
    id: "pq-engine-next",
    beaconId: "proj-engine-next",
    code: "const nextBeacon = nextId ? findBeaconById(nextId) : null;\nreturn { ...state, currentBeacon: nextBeacon, finished: !nextBeacon };",
    question: "Почему используется finished: !nextBeacon вместо finished: !nextId?",
    correct: "findBeaconById() может вернуть null даже если nextId существует — тогда поток завис бы с currentBeacon: null и finished: false",
    wrong: [
      "Это опечатка, оба варианта работают одинаково",
      "nextId может быть undefined если массив children пустой",
      "!nextBeacon короче в написании",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["project", "engine", "next", "bug-fix"],
  },
  {
    id: "pq-mplus-tree",
    beaconId: "proj-mplus-tree",
    code: "// src/phenomenal/mplus/tree.ts\nexport const mplusTree: MplusBeacon[] = [\n  { id: 'mplus-root', children: ['mplus-1','mplus-2','mplus-3'], ... },\n  ...\n]",
    question: "Сколько уровней у дерева M+ в этом проекте?",
    correct: "4 уровня: root (d=1) → M+1/2/3 (d=2) → подузлы (d=3) → листья (d=4)",
    wrong: [
      "2 уровня: root и листья",
      "5 уровней с дополнительным уровнем принципов",
      "3 уровня: root, категории, вопросы",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "mplus", "tree", "structure"],
  },
  {
    id: "pq-select-next",
    beaconId: "proj-select-next",
    code: "// src/phenomenal/mplus/select-next.ts\n// mode 'weighted': узлы с меньшей частотой получают больший вес",
    question: "В чём разница между режимами 'random' и 'weighted' в selectNextBeacon()?",
    correct: "'random' — равная вероятность всех дочерних узлов; 'weighted' — редко посещённые узлы выбираются чаще",
    wrong: [
      "'random' случайный, 'weighted' всегда берёт первый дочерний узел",
      "'weighted' использует importance пользователя, 'random' — importance по умолчанию",
      "Разницы нет — оба режима дают одинаковый результат",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "mplus", "algorithm", "weighted"],
  },
  {
    id: "pq-questions",
    beaconId: "proj-questions",
    code: "// src/phenomenal/r/questions.ts\nexport const questions: RQuestion[] = [\n  { id, beaconId, code, question, correct, wrong: [] }\n]",
    question: "Как вопрос (RQuestion) связан с узлом дерева (MplusBeacon)?",
    correct: "Через два поля: RQuestion.beaconId = MplusBeacon.id и MplusBeacon.questionId = RQuestion.id",
    wrong: [
      "Вопросы не связаны с деревом — они выбираются случайно из глобального массива",
      "Через индекс массива — вопрос №3 соответствует beacon №3",
      "Через тег — поле tags[] должно совпадать с id beacon",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "questions", "beacon", "relation"],
  },
  {
    id: "pq-auth-api",
    beaconId: "proj-auth-api",
    code: "// src/modules/auth/api/auth.api.ts\nexport const authApi = {\n  login: (dto) => fetch('/api/auth/login', { method: 'POST', body: JSON.stringify(dto) }),\n  ...\n}",
    question: "authApi.login() работает в браузере или на сервере?",
    correct: "Только в браузере — это Client-side fetch, вызывается из LoginForm ('use client')",
    wrong: [
      "На сервере — потому что это обычный fetch()",
      "В обоих местах — Next.js изоморфный",
      "В Server Action при отправке формы",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["project", "auth", "client-fetch", "api"],
  },
  {
    id: "pq-login-form",
    beaconId: "proj-login-form",
    code: "'use client';\n// src/modules/auth/components/LoginForm.tsx",
    question: "Почему LoginForm.tsx имеет директиву 'use client'?",
    correct: "Форма использует useState для полей ввода и обработчики событий onChange/onSubmit — это требует клиентского JS",
    wrong: [
      "Потому что делает fetch() запросы",
      "Server Components не могут содержать input элементы",
      "Директива автоматически добавляется к формам Next.js",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "client-component", "form", "auth"],
  },
  {
    id: "pq-stats-card",
    beaconId: "proj-stats-card",
    code: "// src/modules/dashboard/components/StatsCard.tsx",
    question: "StatsCard отображает статистику. Это Server или Client Component?",
    correct: "Server Component — только отображает данные, не нужны хуки или обработчики событий",
    wrong: [
      "Client Component — потому что отображает числа из БД",
      "Оба — гибрид с 'use client' только для анимации",
      "Это не компонент, а Server Action",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["project", "dashboard", "server-component"],
  },
];
