import type { MplusBeacon } from "@/phenomenal/types/mplus";

export const mplusTree: MplusBeacon[] = [
  {
    id: "mplus-root",
    distance: 1,
    questionId: "q-de-1",
    parent: null,
    children: ["mplus-1", "mplus-2", "mplus-3"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-1",
    distance: 2,
    questionId: "q-de-2",
    parent: "mplus-root",
    children: ["mplus-1-1", "mplus-1-2"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-2",
    distance: 2,
    questionId: "q-de-3",
    parent: "mplus-root",
    children: ["mplus-2-1", "mplus-2-2"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-3",
    distance: 2,
    questionId: "q-de-4",
    parent: "mplus-root",
    children: ["mplus-3-1", "mplus-3-2"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-1-1",
    distance: 3,
    questionId: "q-de-5",
    parent: "mplus-1",
    children: ["mplus-4-1"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-1-2",
    distance: 3,
    questionId: "q-de-6",
    parent: "mplus-1",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-2-1",
    distance: 3,
    questionId: "q-de-7",
    parent: "mplus-2",
    children: ["mplus-4-2"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-2-2",
    distance: 3,
    questionId: "q-de-8",
    parent: "mplus-2",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-3-1",
    distance: 3,
    questionId: "q-de-9",
    parent: "mplus-3",
    children: ["mplus-4-3"],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-3-2",
    distance: 3,
    questionId: "q-de-10",
    parent: "mplus-3",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-4-1",
    distance: 4,
    questionId: "q-de-11",
    parent: "mplus-1-1",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-4-2",
    distance: 4,
    questionId: "q-de-12",
    parent: "mplus-2-1",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
  {
    id: "mplus-4-3",
    distance: 4,
    questionId: "q-de-13",
    parent: "mplus-3-1",
    children: [],
    f: 0,
    importance: 1,
    type: ["Mplus"],
  },
];

export function findBeaconById(id: string) {
  return mplusTree.find((b) => b.id === id) ?? null;
}

export function findBeaconByQuestionId(questionId: string) {
  return mplusTree.find((b) => b.questionId === questionId) ?? null;
}
