import type { RQuestion } from "@/phenomenal/types/r";

export const questions: RQuestion[] = [
  {
    id: "q-de-1",
    beaconId: "mplus-root",
    code: "const settings = { theme: 'dark' };",
    question: "Was bewirkt diese Zeile?",
    correct: "Sie erstellt ein Objekt mit der Eigenschaft theme.",
    wrong: [
      "Sie löscht das Objekt settings.",
      "Sie erstellt ein Array mit einem Element.",
      "Sie ruft eine Funktion theme() auf.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "objekte", "grundlagen"],
    principleId: "rf-de-variables",
  },
  {
    id: "q-de-2",
    beaconId: "mplus-1",
    code: "let count = 0; count += 1;",
    question: "Was passiert mit count?",
    correct: "count wird um 1 erhöht.",
    wrong: [
      "count wird auf null gesetzt.",
      "count wird zu einem String.",
      "count bleibt unverändert.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "variablen"],
    principleId: "rf-de-variables",
  },
  {
    id: "q-de-3",
    beaconId: "mplus-2",
    code: "function add(a, b) { return a + b; }",
    question: "Was macht die Funktion add?",
    correct: "Sie gibt die Summe von a und b zurück.",
    wrong: [
      "Sie multipliziert a und b.",
      "Sie gibt immer 0 zurück.",
      "Sie erstellt ein neues Objekt.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "funktionen"],
    principleId: "rf-de-functions",
  },
  {
    id: "q-de-4",
    beaconId: "mplus-3",
    code: "document.getElementById('email').value",
    question: "Wofür steht .value in diesem Ausdruck?",
    correct: "Für den aktuellen Wert des gefundenen Eingabefelds.",
    wrong: [
      "Für die Anzahl der gefundenen Elemente.",
      "Für den HTML-Code des Formulars.",
      "Für die CSS-Klasse des Elements.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "dom", "forms"],
    principleId: "rf-de-dom",
  },
  {
    id: "q-de-5",
    beaconId: "mplus-1-1",
    code: "const names = ['Anna', 'Ben']; names.length",
    question: "Was liefert names.length?",
    correct: "Die Anzahl der Elemente im Array.",
    wrong: [
      "Den letzten Index des Arrays.",
      "Den ersten Eintrag als String.",
      "Die Summe aller Zeichen in den Namen.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "arrays"],
    principleId: "rf-de-arrays",
  },
  {
    id: "q-de-6",
    beaconId: "mplus-1-2",
    code: "const doubled = [1,2,3].map(n => n * 2);",
    question: "Was ist doubled?",
    correct: "Ein neues Array mit verdoppelten Werten.",
    wrong: [
      "Die Zahl 12.",
      "Dasselbe Array wie vorher, ohne Änderungen.",
      "Ein Objekt mit den Werten als Keys.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "arrays", "map"],
    principleId: "rf-de-arrays",
  },
  {
    id: "q-de-7",
    beaconId: "mplus-2-1",
    code: "const even = [1,2,3,4].filter(n => n % 2 === 0);",
    question: "Welches Ergebnis hat even?",
    correct: "[2, 4]",
    wrong: [
      "[1, 3]",
      "[1, 2, 3, 4]",
      "2",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "arrays", "filter"],
    principleId: "rf-de-arrays",
  },
  {
    id: "q-de-8",
    beaconId: "mplus-2-2",
    code: "const sum = [1,2,3].reduce((a, n) => a + n, 0);",
    question: "Wofür wird reduce hier genutzt?",
    correct: "Zum Aufsummieren aller Array-Werte.",
    wrong: [
      "Zum Sortieren des Arrays.",
      "Zum Entfernen von Duplikaten.",
      "Zum Umwandeln in ein Objekt.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "arrays", "reduce"],
    principleId: "rf-de-arrays",
  },
  {
    id: "q-de-9",
    beaconId: "mplus-3-1",
    code: "const text = input?.trim();",
    question: "Was macht der Operator ?. in diesem Beispiel?",
    correct: "Er verhindert einen Fehler, wenn input null/undefined ist.",
    wrong: [
      "Er konvertiert input automatisch in eine Zahl.",
      "Er ruft trim zweimal auf.",
      "Er erstellt ein neues DOM-Element.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "optional-chaining"],
    principleId: "rf-de-functions",
  },
  {
    id: "q-de-10",
    beaconId: "mplus-3-2",
    code: "const button = document.querySelector('button');",
    question: "Was liefert querySelector('button')?",
    correct: "Das erste passende Button-Element oder null.",
    wrong: [
      "Alle Buttons als Array.",
      "Nur den Text des Buttons.",
      "Immer ein neues Button-Element.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "dom", "querySelector"],
    principleId: "rf-de-dom",
  },
  {
    id: "q-de-11",
    beaconId: "mplus-4-1",
    code: "const data = await fetch('/api/items').then(r => r.json());",
    question: "Was beschreibt await in dieser Zeile am besten?",
    correct: "Es wartet auf die Promise-Auflösung vor der Weiterverarbeitung.",
    wrong: [
      "Es wiederholt die Anfrage automatisch dreimal.",
      "Es macht die Funktion synchron ohne Promise.",
      "Es speichert Daten automatisch im Local Storage.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "async", "fetch"],
    principleId: "rf-de-async",
  },
  {
    id: "q-de-12",
    beaconId: "mplus-4-2",
    code: "setTimeout(() => console.log('tick'), 1000);",
    question: "Welche Aussage ist korrekt?",
    correct: "Der Callback läuft frühestens nach etwa 1000 ms.",
    wrong: [
      "Der Callback läuft sofort synchron.",
      "setTimeout blockiert den gesamten Thread.",
      "Der Callback läuft genau in jedem Fall nach 1000.000 ms.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "async", "event-loop"],
    principleId: "rf-de-async",
  },
  {
    id: "q-de-13",
    beaconId: "mplus-4-3",
    code: "function outer(){ let x = 1; return () => x; }",
    question: "Warum kann die innere Funktion weiterhin auf x zugreifen?",
    correct: "Wegen einer Closure über den lexikalischen Scope.",
    wrong: [
      "Weil x global deklariert wurde.",
      "Weil return alle Variablen kopiert.",
      "Weil JavaScript Parameter zwischenspeichert.",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["javascript", "closure", "scope"],
    principleId: "rf-de-scope",
  },
];
