import type { RQuestion } from "@/phenomenal/types/r";

/**
 * Fragen über die Projektstruktur von next-learning.
 * Jede Frage ist an einen Beacon-Knoten im M+-Baum gebunden.
 * Sprache: Deutsch.
 */
export const questions: RQuestion[] = [

  // ── Ebene 1: Wurzel ──────────────────────────────────────────────────────
  {
    id: "pq-root",
    beaconId: "mplus-root",
    code: "next-learning/",
    question: "Auf welchem Framework basiert diese Anwendung?",
    correct: "Next.js 16 mit App Router und React 19",
    wrong: [
      "Vite + Vue 3",
      "Create React App (CRA)",
      "Remix + React 18",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "nextjs", "framework"],
    principleId: "rf-proj-layers",
  },

  // ── Ebene 2: Schichten ────────────────────────────────────────────────────
  {
    id: "pq-app",
    beaconId: "proj-app",
    code: "src/app/",
    question: "Was befindet sich im Ordner src/app/?",
    correct: "Seiten, API-Routen und Server Actions — das Routing des Next.js App Routers",
    wrong: [
      "Nur React-Komponenten ohne Routen",
      "Nur statische Dateien (CSS, Bilder)",
      "Business-Logik und Quiz-Engine",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "app-router", "routing"],
    principleId: "rf-proj-layers",
  },
  {
    id: "pq-core",
    beaconId: "proj-core",
    code: "src/core/",
    question: "Was befindet sich im Ordner src/core/?",
    correct: "Infrastruktur: Datenbankanbindung, Authentifizierung (JWT, bcrypt), Konfiguration",
    wrong: [
      "UI-Komponenten für Buttons und Inputs",
      "Quiz-Engine: start, answer, next, finish",
      "Daten der Fragen und Prinzipien",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "core", "infrastruktur"],
    principleId: "rf-proj-layers",
  },
  {
    id: "pq-phenomenal",
    beaconId: "proj-phenomenal",
    code: "src/phenomenal/",
    question: "Was enthält der Ordner src/phenomenal/?",
    correct: "Die gesamte Quiz-Engine: M+-Baum, Fragen, Engine-Funktionen, UI-Komponenten, Typen",
    wrong: [
      "Nur REST-API-Routen",
      "Nur die Datenbankverbindung",
      "Nur React-Hooks",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "phenomenal", "quiz-engine"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-modules",
    beaconId: "proj-modules",
    code: "src/modules/",
    question: "Nach welchem Prinzip sind die Dateien in src/modules/ organisiert?",
    correct: "Nach Features (Feature-Module): auth, dashboard, users — jedes mit eigenen api/, components/, model/",
    wrong: [
      "Nach Dateitypen: alle Komponenten zusammen, alle Typen zusammen",
      "Pro Seite: ein Modul = eine Seite",
      "Alphabetisch ohne inhaltliche Bedeutung",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "module", "architektur"],
    principleId: "rf-proj-layers",
  },
  {
    id: "pq-shared",
    beaconId: "proj-shared",
    code: "src/shared/",
    question: "Was befindet sich in src/shared/?",
    correct: "Wiederverwendbare Hilfsmittel und UI-Primitiven: Button, Card, Input, cn(), formatDate, Hooks",
    wrong: [
      "Geheimschlüssel und Umgebungsvariablen",
      "Drizzle ORM Tabellenschemata",
      "Server Actions für Formulare",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "shared", "hilfsmittel"],
    principleId: "rf-proj-layers",
  },

  // ── Ebene 3: Teilsysteme ──────────────────────────────────────────────────
  {
    id: "pq-app-routing",
    beaconId: "proj-app-routing",
    code: "src/app/page.tsx\nsrc/app/layout.tsx",
    question: "Was macht die Datei src/app/layout.tsx im Next.js App Router?",
    correct: "Umschließt alle Seiten: setzt Schriften, <html>, <body> und globale Stile",
    wrong: [
      "Speichert Routen als Array von Pfaden",
      "Verantwortlich nur für das Routing zwischen /quiz und /auth",
      "Ist ein Server Action für die Navigation",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "layout", "app-router"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-app-actions",
    beaconId: "proj-app-actions",
    code: "// src/app/actions/flows.actions.ts\n'use server';",
    question: "Was ist ein Server Action und was bewirkt die Direktive 'use server'?",
    correct: "Markiert eine Funktion als serverseitig — Next.js führt sie auf dem Server aus, Aufruf aus Client Component ohne fetch() möglich",
    wrong: [
      "Startet die Funktion in einem Web Worker des Browsers",
      "Cached das Ergebnis der Funktion für 60 Sekunden",
      "Wandelt die Funktion in eine API Route um",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "server-action", "nextjs"],
    principleId: "rf-proj-server-action",
  },
  {
    id: "pq-app-api",
    beaconId: "proj-app-api",
    code: "src/app/api/auth/login/route.ts",
    question: "Wie erkennt Next.js, dass eine Datei eine API Route ist?",
    correct: "Über den Dateinamen route.ts im Ordner app/api/ — sie exportiert Funktionen GET, POST usw.",
    wrong: [
      "Über einen speziellen @ApiRoute-Dekorator über der Funktion",
      "Über die Dateiendung .api.ts",
      "Über den Eintrag in next.config.ts",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "api-route", "nextjs"],
    principleId: "rf-proj-server-action",
  },
  {
    id: "pq-core-auth",
    beaconId: "proj-core-auth",
    code: "src/core/auth/",
    question: "Welche zwei Technologien werden für die Authentifizierung in src/core/auth/ eingesetzt?",
    correct: "bcryptjs — Passwort-Hashing, jose — Erstellen und Prüfen von JWT-Tokens",
    wrong: [
      "passport.js und express-session",
      "Auth.js (NextAuth) und Prisma",
      "Firebase Auth und Google OAuth",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "auth", "bcrypt", "jwt"],
    principleId: "rf-proj-auth",
  },
  {
    id: "pq-core-db",
    beaconId: "proj-core-db",
    code: "src/core/db/",
    question: "Welche Datenbank und welches ORM werden im Projekt verwendet?",
    correct: "Neon PostgreSQL (serverless) + Drizzle ORM",
    wrong: [
      "SQLite + Prisma ORM",
      "MongoDB Atlas + Mongoose",
      "PlanetScale MySQL + TypeORM",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "datenbank", "drizzle", "neon"],
    principleId: "rf-proj-db",
  },
  {
    id: "pq-engine",
    beaconId: "proj-engine",
    code: "src/phenomenal/engine/",
    question: "Alle Funktionen in src/phenomenal/engine/ sind reine Funktionen. Was bedeutet das?",
    correct: "Sie verändern keinen externen Zustand — sie empfangen einen QuizState und geben einen neuen QuizState zurück",
    wrong: [
      "Sie werden nur auf dem Server ausgeführt",
      "Sie speichern das Ergebnis automatisch im localStorage",
      "Sie sind React-Hooks",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "engine", "pure-functions"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-mplus",
    beaconId: "proj-mplus",
    code: "src/phenomenal/mplus/",
    question: "Was ist ein Beacon (Knoten) im M+-System?",
    correct: "Ein Knoten des Navigationsbaums — speichert einen Verweis auf eine Frage (questionId), Kindknoten und Häufigkeitsstatistik",
    wrong: [
      "Eine React-Komponente zur Anzeige einer Frage",
      "Eine HTTP-Anfrage an das API für die nächste Frage",
      "Ein Eintrag in der Tabelle quiz_flow_steps",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "mplus", "beacon", "baum"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-r",
    beaconId: "proj-r",
    code: "src/phenomenal/r/questions.ts",
    question: "Was enthält der Ordner src/phenomenal/r/?",
    correct: "Fragen (RQuestion): Text, richtige Antwort, drei falsche Optionen, Tags",
    wrong: [
      "Prinzipien und Regeln (rf-System)",
      "Ein HTTP-Client zum Laden von Fragen vom Server",
      "Ergebnisse abgeschlossener Durchläufe",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "fragen", "r-system"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-mod-auth",
    beaconId: "proj-mod-auth",
    code: "src/modules/auth/",
    question: "Was unterscheidet src/modules/auth/ von src/core/auth/?",
    correct: "modules/auth — UI und fetch-Client (LoginForm, SignupForm, authApi); core/auth — Serverlogik (JWT, bcrypt, guards)",
    wrong: [
      "modules/auth für Seiten, core/auth für Tests",
      "modules/auth für Next.js 16, core/auth für ältere Versionen",
      "Kein Unterschied, es ist Code-Duplizierung",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "auth", "module", "trennung"],
    principleId: "rf-proj-layers",
  },
  {
    id: "pq-mod-dashboard",
    beaconId: "proj-mod-dashboard",
    code: "src/modules/dashboard/components/DashboardGrid.tsx",
    question: "Was zeigt DashboardGrid im Modul dashboard?",
    correct: "Ein Raster von Statistikkarten: Score, Wichtigkeit, Anzahl der gespeicherten Durchläufe",
    wrong: [
      "Den M+-Baum als SVG-Grafik",
      "Eine Tabelle aller Fragen mit Filterung",
      "Ein Formular zur Erstellung eines neuen Quiz",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "dashboard", "ui"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-shared-ui",
    beaconId: "proj-shared-ui",
    code: "src/shared/ui/Button.tsx\nsrc/shared/ui/Card.tsx\nsrc/shared/ui/Input.tsx",
    question: "Wozu dienen Button, Card, Input in src/shared/ui/?",
    correct: "Wiederverwendbare Primitiven mit einheitlichen Stilen — um Tailwind-Klassen nicht überall zu duplizieren",
    wrong: [
      "Das sind Kopien von shadcn/ui-Komponenten",
      "Sie werden nur für /auth-Seiten benötigt",
      "Sie sind automatisch von Next.js generierte Dateien",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "shared", "ui-primitiven"],
    principleId: "rf-proj-layers",
  },
  {
    id: "pq-shared-lib",
    beaconId: "proj-shared-lib",
    code: "// src/shared/lib/cn.ts\nexport const cn = (...inputs) => twMerge(clsx(inputs));",
    question: "Was macht die Funktion cn() aus src/shared/lib/cn.ts?",
    correct: "Kombiniert className-Strings mit Deduplizierung über clsx — nützlich für bedingte Tailwind-Klassen",
    wrong: [
      "Bindet CSS-Module an eine Komponente",
      "Wandelt px-Werte in rem um für Responsive Design",
      "Generiert eindeutige CSS-Variablen",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "shared", "cn", "tailwind"],
    principleId: "rf-proj-layers",
  },

  // ── Ebene 4: Konkrete Dateien ─────────────────────────────────────────────
  {
    id: "pq-app-page",
    beaconId: "proj-app-page",
    code: "// src/app/page.tsx\nexport default function HomePage() { ... }",
    question: "Ist src/app/page.tsx ein Server Component oder Client Component?",
    correct: "Server Component — keine 'use client'-Direktive, wird auf dem Server ausgeführt, HTML geht an den Browser",
    wrong: [
      "Client Component — weil es JSX enthält",
      "Hybrid — erste Render auf Server, zweite auf Client",
      "API Route — weil es im Ordner app/ liegt",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "server-component", "seite"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-app-layout",
    beaconId: "proj-app-layout",
    code: "// src/app/layout.tsx\nexport default function RootLayout({ children }) {}",
    question: "Wie oft rendert Next.js layout.tsx bei der Navigation zwischen Seiten?",
    correct: "Nur einmal beim ersten Laden — bei Client-Navigation wird layout nicht neu gerendert",
    wrong: [
      "Bei jedem Seitenwechsel",
      "Niemals — es wird nur auf dem Client ausgeführt",
      "Zweimal: bei SSR und bei Hydratation",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "layout", "nextjs", "rendering"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-save-flow-action",
    beaconId: "proj-save-flow-action",
    code: "'use server';\nexport async function saveFlowAction(flow, sequence) {\n  const session = await readSessionFromCookie();\n  if (!session) return { ok: false, reason: 'not_authenticated' };\n  await saveFlowForUser(...);\n  return { ok: true };\n}",
    question: "Was passiert, wenn saveFlowAction() { ok: false, reason: 'not_authenticated' } zurückgibt?",
    correct: "QuizPage wechselt zum Fallback: speichert den Durchlauf im localStorage über saveFlow()",
    wrong: [
      "Die App wirft einen 401-Fehler und leitet auf /auth weiter",
      "Der Durchlauf geht verloren — weder DB noch localStorage",
      "Server Action wiederholt den Versuch automatisch nach 3 Sekunden",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["projekt", "server-action", "fallback", "auth"],
    principleId: "rf-proj-fallback",
  },
  {
    id: "pq-api-auth",
    beaconId: "proj-api-auth",
    code: "// POST /api/auth/login\nconst { email, password } = await req.json();\nconst user = await findUserByEmail(email);\nconst ok = await verifyPassword(password, user.passwordHash);",
    question: "Wo wird das Sitzungs-Token nach erfolgreicher Anmeldung gespeichert?",
    correct: "In einem httpOnly-Cookie nl_session — der Browser kann es nicht per JavaScript lesen (Schutz vor XSS)",
    wrong: [
      "Im localStorage unter dem Schlüssel 'token'",
      "Im React-State über useState",
      "Im sessionStorage, wird beim Schließen des Tabs gelöscht",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "auth", "cookie", "sicherheit"],
    principleId: "rf-proj-auth",
  },
  {
    id: "pq-api-flows",
    beaconId: "proj-api-flows",
    code: "// GET /api/flows — gibt Durchläufe des Nutzers zurück\n// POST /api/flows — speichert einen Durchlauf",
    question: "Wozu wird /api/flows benötigt, wenn es den Server Action saveFlowAction() gibt?",
    correct: "flowsApi.list() liest die Liste vom Server — Server Action speichert nur, GET wird zum Laden benötigt",
    wrong: [
      "Das ist veralteter Code, der nicht mehr verwendet wird",
      "Server Action kann keine Daten zurückgeben, nur speichern",
      "/api/flows für anonyme Nutzer, Server Action für eingeloggte",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "api", "flows", "server-action"],
    principleId: "rf-proj-server-action",
  },
  {
    id: "pq-session",
    beaconId: "proj-session",
    code: "// src/core/auth/session.ts\nexport async function readSessionFromCookie(): Promise<JwtPayload | null>",
    question: "Was macht readSessionFromCookie() in session.ts?",
    correct: "Liest Cookie nl_session, verifiziert die JWT-Signatur über jose und gibt den Payload mit userId (sub) zurück",
    wrong: [
      "Liest userId aus localStorage",
      "Macht einen fetch zu /api/auth/me zur Token-Prüfung",
      "Erstellt eine neue Sitzung, wenn die alte abgelaufen ist",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["projekt", "session", "jwt", "cookie"],
    principleId: "rf-proj-auth",
  },
  {
    id: "pq-password",
    beaconId: "proj-password",
    code: "// src/core/auth/password.ts\nawait bcrypt.hash(password, 12)\nawait bcrypt.compare(password, hash)",
    question: "Warum wird bcrypt mit rounds=12 statt einfachem SHA-256 verwendet?",
    correct: "bcrypt ist absichtlich langsam — das Prüfen eines Passworts dauert ~250ms, was Brute-Force praktisch unmöglich macht",
    wrong: [
      "SHA-256 wird in Node.js nicht unterstützt",
      "bcrypt ist kürzer im Code, daher gewählt",
      "bcrypt speichert das Salt separat in der DB, SHA-256 nicht",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "passwort", "bcrypt", "sicherheit"],
    principleId: "rf-proj-auth",
  },
  {
    id: "pq-guards",
    beaconId: "proj-guards",
    code: "// src/core/auth/guards.ts\nexport async function requireAuth(req: Request): Promise<JwtPayload>",
    question: "Was macht requireAuth() und wo wird sie verwendet?",
    correct: "Prüft die Sitzung in einem API Route — falls nicht eingeloggt, wirft sie einen 401-Fehler; genutzt in route.ts als Guard",
    wrong: [
      "Leitet den Nutzer über redirect() zu /auth weiter",
      "Prüft Zugriffsrechte (admin/user) für Routen",
      "Wird in Client Components zur Absicherung von Buttons verwendet",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "guards", "auth", "api"],
    principleId: "rf-proj-auth",
  },
  {
    id: "pq-schema",
    beaconId: "proj-schema",
    code: "export const users = pgTable('users', { ... })\nexport const quizFlows = pgTable('quiz_flows', { ... })\nexport const quizFlowSteps = pgTable('quiz_flow_steps', { ... })",
    question: "Wie viele Tabellen sind in schema.ts definiert und was speichern sie?",
    correct: "3 Tabellen: users (Konten), quiz_flows (ein ganzer Durchlauf), quiz_flow_steps (jeder Schritt)",
    wrong: [
      "5 Tabellen: sessions und principles kommen hinzu",
      "2 Tabellen: users und flows (Schritte als JSON in flows)",
      "1 Tabelle: alles als JSONB in quiz_data",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "schema", "datenbank", "drizzle"],
    principleId: "rf-proj-db",
  },
  {
    id: "pq-flows-db",
    beaconId: "proj-flows-db",
    code: "await db.transaction(async (trx) => {\n  await trx.insert(quizFlows).values(...);\n  await trx.insert(quizFlowSteps).values(...);\n});",
    question: "Warum verwendet saveFlowForUser() eine Transaktion?",
    correct: "Damit quiz_flows und quiz_flow_steps atomar geschrieben werden — entweder beide erfolgreich oder keiner",
    wrong: [
      "Eine Transaktion beschleunigt zwei INSERT-Befehle",
      "Drizzle erfordert Transaktionen für alle INSERT-Operationen",
      "Transaktionen umgehen Begrenzungen der Anfragegröße",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["projekt", "datenbank", "transaktion", "drizzle"],
    principleId: "rf-proj-db",
  },
  {
    id: "pq-engine-start",
    beaconId: "proj-engine-start",
    code: "export function startQuiz(mode = 'random'): QuizState {\n  return {\n    currentBeacon: findBeaconById('mplus-root'),\n    steps: [],\n    finished: false,\n    mode,\n  };\n}",
    question: "Mit welchem Knoten beginnt das Quiz immer und warum?",
    correct: "Mit 'mplus-root' — dem Wurzelknoten des M+-Baums, dem einzigen Knoten ohne parent (parent: null)",
    wrong: [
      "Mit einem zufälligen Blattknoten für Abwechslung",
      "Mit dem Knoten mit der größten Wichtigkeit",
      "Mit dem zuletzt besuchten Knoten aus dem localStorage",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "engine", "start", "mplus"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-engine-answer",
    beaconId: "proj-engine-answer",
    code: "updateQuestion(question.id, { importance, incrementFrequency: true });\nupdateBeaconFrequency(beacon.id);\nupdateBeaconImportance(beacon.id, importance);",
    question: "Wo wird die aktualisierte Statistik der Fragen nach der Antwort gespeichert?",
    correct: "Im Arbeitsspeicher (in-memory) — in den Arrays questions[] und mplusTree[]; beim Neuladen der Seite wird sie zurückgesetzt",
    wrong: [
      "Sofort in Neon PostgreSQL über Drizzle",
      "Im localStorage über saveFlow()",
      "Im React-State über useState in QuizPage",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["projekt", "engine", "antwort", "zustand"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-engine-next",
    beaconId: "proj-engine-next",
    code: "const nextBeacon = nextId ? findBeaconById(nextId) : null;\nreturn { ...state, currentBeacon: nextBeacon, finished: !nextBeacon };",
    question: "Warum wird finished: !nextBeacon statt finished: !nextId verwendet?",
    correct: "findBeaconById() kann null zurückgeben, selbst wenn nextId existiert — dann würde der Durchlauf einfrieren mit currentBeacon: null und finished: false",
    wrong: [
      "Das ist ein Tippfehler, beide Varianten funktionieren gleich",
      "nextId kann undefined sein, wenn children leer ist",
      "!nextBeacon ist kürzer zu schreiben",
    ],
    comments: [],
    importance: 3,
    f: 0,
    tags: ["projekt", "engine", "next", "bugfix"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-mplus-tree",
    beaconId: "proj-mplus-tree",
    code: "export const mplusTree: MplusBeacon[] = [\n  { id: 'mplus-root', children: ['proj-app','proj-core',...], ... },\n  ...\n]",
    question: "Wie viele Ebenen hat der M+-Baum in diesem Projekt?",
    correct: "4 Ebenen: Wurzel (d=1) → Schichten (d=2) → Teilsysteme (d=3) → Dateien/Blätter (d=4)",
    wrong: [
      "2 Ebenen: Wurzel und Blätter",
      "5 Ebenen mit einer zusätzlichen Prinzipienebene",
      "3 Ebenen: Wurzel, Kategorien, Fragen",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "mplus", "baum", "struktur"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-select-next",
    beaconId: "proj-select-next",
    code: "// mode 'weighted': Knoten mit niedrigerer Häufigkeit erhalten mehr Gewicht",
    question: "Was ist der Unterschied zwischen den Modi 'random' und 'weighted' in selectNextBeacon()?",
    correct: "'random' — gleiche Wahrscheinlichkeit aller Kindknoten; 'weighted' — seltener besuchte Knoten werden häufiger gewählt",
    wrong: [
      "'random' zufällig, 'weighted' wählt immer den ersten Kindknoten",
      "'weighted' nutzt die Benutzerpräferenz, 'random' die Standard-Wichtigkeit",
      "Kein Unterschied — beide Modi liefern das gleiche Ergebnis",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "mplus", "algorithmus", "weighted"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-questions",
    beaconId: "proj-questions",
    code: "export const questions: RQuestion[] = [\n  { id, beaconId, code, question, correct, wrong: [] }\n]",
    question: "Wie ist eine Frage (RQuestion) mit einem Baumknoten (MplusBeacon) verbunden?",
    correct: "Über zwei Felder: RQuestion.beaconId = MplusBeacon.id und MplusBeacon.questionId = RQuestion.id",
    wrong: [
      "Fragen sind nicht mit dem Baum verbunden — sie werden zufällig gewählt",
      "Über den Array-Index — Frage Nr. 3 entspricht Beacon Nr. 3",
      "Über Tags — tags[] muss mit der Beacon-ID übereinstimmen",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "fragen", "beacon", "verbindung"],
    principleId: "rf-proj-engine",
  },
  {
    id: "pq-auth-api",
    beaconId: "proj-auth-api",
    code: "// src/modules/auth/api/auth.api.ts\nexport const authApi = {\n  login: (dto) => fetch('/api/auth/login', { method: 'POST', body: JSON.stringify(dto) }),\n}",
    question: "Läuft authApi.login() im Browser oder auf dem Server?",
    correct: "Nur im Browser — das ist ein clientseitiger fetch, aufgerufen aus LoginForm ('use client')",
    wrong: [
      "Auf dem Server — weil es ein normaler fetch() ist",
      "In beiden Umgebungen — Next.js ist isomorph",
      "In einem Server Action bei der Formularabsendung",
    ],
    comments: [],
    importance: 2,
    f: 0,
    tags: ["projekt", "auth", "client-fetch", "api"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-login-form",
    beaconId: "proj-login-form",
    code: "'use client';\n// src/modules/auth/components/LoginForm.tsx",
    question: "Warum hat LoginForm.tsx die Direktive 'use client'?",
    correct: "Das Formular verwendet useState für Eingabefelder und Ereignishandler onChange/onSubmit — das erfordert clientseitiges JS",
    wrong: [
      "Weil es fetch()-Anfragen macht",
      "Server Components können keine input-Elemente enthalten",
      "Die Direktive wird automatisch zu Formularen in Next.js hinzugefügt",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "client-component", "formular", "auth"],
    principleId: "rf-proj-server-client",
  },
  {
    id: "pq-stats-card",
    beaconId: "proj-stats-card",
    code: "// src/modules/dashboard/components/StatsCard.tsx",
    question: "StatsCard zeigt Statistiken an. Ist es ein Server oder Client Component?",
    correct: "Server Component — zeigt nur Daten an, keine Hooks oder Ereignishandler nötig",
    wrong: [
      "Client Component — weil es Zahlen aus der DB anzeigt",
      "Beides — Hybrid mit 'use client' nur für Animationen",
      "Das ist kein Komponenten, sondern ein Server Action",
    ],
    comments: [],
    importance: 1,
    f: 0,
    tags: ["projekt", "dashboard", "server-component"],
    principleId: "rf-proj-server-client",
  },
];
